# 冒号后面用空格，不然无法使用

#表示使用哪个配置文件
#spring:
#    profiles:
#        active: dev


spring:
    profiles:
        active: ${IFW_ENV}
    application.name: hello-server  #Eureka服务命名
    
eureka:
    client:
        serviceUrl:
            #defaultZone: http://localhost:1111/eureka #指定服务注册中心的地址
            defaultZone: http://peer1:1111/eureka/,http://peer2:1112/eureka/ #指定服务注册中心的地址

server:
    port: 8080
    
#book:
#    name: SpringCloud
#    number: 随机字符串：${random.value} , 随机int：${random.int} , 随机long：${random.long} ,10以内随机数：${random.int(10)} ,10~20随机数：${random.int[10,20]}
#   desc: ${book.name} write by ${book.author}
    

    


    